/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;

/**
 *
 * @author Owner
 */
public class Logged_In extends javax.swing.JFrame implements Runnable, interfaces.userinterface {

    boolean logged_In;
    boolean isLoaded;
    UI.graphical_UI gui;
    String user;
    command_handler.loggedInCommand_handler cmd_handler;
    
    
    /**
     * Creates new form Logged_In
     * @param logged_In
     * @param gui
     * @param user
     */
    public Logged_In(boolean logged_In, UI.graphical_UI gui, String user) {
        initComponents();
        welcome_user.setText("Welcome " + user);
        this.logged_In = logged_In;
        this.gui = gui;
        this.user = user;
        this.isLoaded = false;
        enter_payment_util_type.setVisible(false);
    }
    
    public void init()
    {
        //what to do when logged in
    }
    
    
    public void setMessage(String message)
    {
        personal_message_text_area.setText(message);
    }
    
    @Override
    public void run()
    {
        if (logged_In == true)
        {
            this.setVisible(true);
        }
//        while (this.isLoaded == false)
//        {
//            String filename = "messages.txt";
//            cmd_handler.hanfleFile(filename);
//            this.isLoaded = true;
//        }
//
//Pretty ,uch load any new message that could be in the init function
    }
    
    public void setCommandHandler(command_handler.loggedInCommand_handler cmd_handler)
    {
        this.cmd_handler = cmd_handler;
    }
    
    @Override
    public void update(String command, String Type)
    {
        if (Type.equals("Logged_In"))
        {
            System.out.println(command);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log_out = new javax.swing.JButton();
        bills = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        confirm_payment_amount_paid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        confirm_payment_date_paid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        confirm_payment_person_paid = new javax.swing.JTextField();
        confirm_payment_submit_btn = new javax.swing.JButton();
        confirm_payment_reset_btn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        show_hide_enter_bill_tab = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        personal_message_text_area = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panel_for_enter_bill = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        enter_bill_date_label = new javax.swing.JLabel();
        enter_bill_date = new javax.swing.JTextField();
        enter_bill_item = new javax.swing.JTextField();
        enter_bill_item_label = new javax.swing.JLabel();
        enter_bill_submit_button = new javax.swing.JButton();
        enter_bill_reset_button = new javax.swing.JButton();
        enter_bill_amount_label = new javax.swing.JLabel();
        enter_bill_amount = new javax.swing.JTextField();
        enter_payment_bill = new javax.swing.JComboBox<>();
        enter_details_isSelected = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        enter_payment_util_type = new javax.swing.JComboBox<>();
        enter_payment_isSubmitted = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        back_to_main = new javax.swing.JButton();
        welcome_user = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        enter_payment_menu_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        log_out.setText("Log Out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        bills.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Hello Silverstoners");

        jLabel2.setText("View the bills and othe rstuffs related to our house");

        jLabel3.setText("Hope you engoy this pc applicaction with java");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 331, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        bills.addTab("Home", jPanel1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", jPanel5);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab2", jPanel6);

        bills.addTab("Bills", jTabbedPane3);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Kome", "Alex", "Jeremy", "Mark", "Hans"},
                {"Hans", "Mark", "Kome", "Alex", "Jeremy"},
                {"Heremy", "Alex", "Hans", "MArk", "Kome"},
                {"Hans", "Mark", "Kome", "Alex", "Jeremy"},
                {"Hans", "Alex", "Jeremy", "MArk", "Kome"}
            },
            new String [] {
                "Up Vaccum", "Down Vaccum", "Up Bath", "Down Bath", "Outside"
            }
        ));
        jTable3.setAlignmentX(0.6F);
        jScrollPane1.setViewportView(jTable3);

        bills.addTab("Chores", jScrollPane1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("                             Confirm Payment");

        jLabel7.setText("Amount Paid");

        confirm_payment_amount_paid.setText("Enter the amount paid to you");
        confirm_payment_amount_paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_payment_amount_paidActionPerformed(evt);
            }
        });

        jLabel8.setText("Date Paid");

        jLabel9.setText("in $CAD");

        confirm_payment_date_paid.setText("Enter the date of the Payment");

        jLabel10.setText("Paid By");

        confirm_payment_person_paid.setText("Enter the name of the person who paid you");

        confirm_payment_submit_btn.setText("Submit");
        confirm_payment_submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_payment_submit_btnActionPerformed(evt);
            }
        });

        confirm_payment_reset_btn.setText("Reset");
        confirm_payment_reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_payment_reset_btnActionPerformed(evt);
            }
        });

        jLabel19.setText("dd/mm/yyyy");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Utility", "Non-Utility" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel22.setText("Paid For");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(confirm_payment_submit_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(confirm_payment_reset_btn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel22))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(confirm_payment_amount_paid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirm_payment_date_paid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirm_payment_person_paid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel19))))))
                .addGap(39, 39, 39))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(confirm_payment_amount_paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(confirm_payment_date_paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_payment_person_paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_payment_submit_btn)
                    .addComponent(confirm_payment_reset_btn))
                .addContainerGap())
        );

        bills.addTab("Confirm payment", jPanel7);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Settings");

        jLabel21.setText("Show/Hide Confrim Payment option");

        show_hide_enter_bill_tab.setText("Hide");
        show_hide_enter_bill_tab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_hide_enter_bill_tabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(show_hide_enter_bill_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel20)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(show_hide_enter_bill_tab))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bills.addTab("Other", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        personal_message_text_area.setColumns(20);
        personal_message_text_area.setRows(5);
        jScrollPane4.setViewportView(personal_message_text_area);

        jLabel5.setBackground(new java.awt.Color(51, 153, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Messages");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panel_for_enter_bill.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setText("Enter Details of Purchase/Payment Made");

        enter_bill_date_label.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        enter_bill_date_label.setText("Date of Purchased Item");

        enter_bill_item.setToolTipText("Leave blank if utility bill");

        enter_bill_item_label.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        enter_bill_item_label.setText("Item Purchased");

        enter_bill_submit_button.setText("Submit");
        enter_bill_submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_bill_submit_buttonActionPerformed(evt);
            }
        });

        enter_bill_reset_button.setText("Reset");

        enter_bill_amount_label.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        enter_bill_amount_label.setText("Amount Purchased");

        enter_bill_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_bill_amountActionPerformed(evt);
            }
        });

        enter_payment_bill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an Item", "Non-Utility Bill", "Utility Bill" }));
        enter_payment_bill.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                enter_payment_billItemStateChanged(evt);
            }
        });
        enter_payment_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_payment_billActionPerformed(evt);
            }
        });

        enter_details_isSelected.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        enter_details_isSelected.setText("Utility or Non_Util");

        jLabel16.setText("in $");

        jLabel17.setText("name");

        jLabel18.setText("dd/mm/yyyy");

        enter_payment_util_type.setEditable(true);
        enter_payment_util_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hydro", "Water", "Internet" }));
        enter_payment_util_type.setToolTipText("Select utility bill name");

        enter_payment_isSubmitted.setText(" ");

        javax.swing.GroupLayout panel_for_enter_billLayout = new javax.swing.GroupLayout(panel_for_enter_bill);
        panel_for_enter_bill.setLayout(panel_for_enter_billLayout);
        panel_for_enter_billLayout.setHorizontalGroup(
            panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_for_enter_billLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enter_bill_date_label)
                    .addComponent(enter_bill_item_label)
                    .addComponent(enter_bill_amount_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_for_enter_billLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_for_enter_billLayout.createSequentialGroup()
                        .addGroup(panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enter_bill_item)
                            .addComponent(enter_bill_date)
                            .addComponent(enter_bill_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_for_enter_billLayout.createSequentialGroup()
                                .addGroup(panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel_for_enter_billLayout.createSequentialGroup()
                                        .addComponent(enter_bill_submit_button)
                                        .addGap(18, 18, 18)
                                        .addComponent(enter_payment_isSubmitted)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(enter_bill_reset_button))
                                    .addGroup(panel_for_enter_billLayout.createSequentialGroup()
                                        .addComponent(enter_details_isSelected)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(enter_payment_util_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(enter_payment_bill, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(16, 16, 16))
                            .addGroup(panel_for_enter_billLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        panel_for_enter_billLayout.setVerticalGroup(
            panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_for_enter_billLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter_bill_date_label)
                    .addComponent(enter_bill_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_payment_bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_details_isSelected)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter_bill_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_bill_item_label)
                    .addComponent(jLabel17)
                    .addComponent(enter_payment_util_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel_for_enter_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter_bill_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_bill_amount_label)
                    .addComponent(enter_bill_submit_button)
                    .addComponent(enter_bill_reset_button)
                    .addComponent(jLabel16)
                    .addComponent(enter_payment_isSubmitted))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_for_enter_bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_for_enter_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setText("Details In the tables above are up for review - Contact your Admin @ komemichael@gmail.com");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        back_to_main.setText("Back");
        back_to_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_to_mainActionPerformed(evt);
            }
        });

        welcome_user.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        welcome_user.setText("Welcome SilverStonite");

        jMenu1.setText("File");

        jMenuItem1.setText("Chores");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Non-Utility Bills");
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Utility Bills");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        enter_payment_menu_item.setText("Enter payment");
        enter_payment_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_payment_menu_itemActionPerformed(evt);
            }
        });
        jMenu2.add(enter_payment_menu_item);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(welcome_user, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(222, 222, 222))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bills)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(log_out)
                                .addGap(29, 29, 29)
                                .addComponent(back_to_main, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(welcome_user)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bills, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(log_out)
                    .addComponent(back_to_main))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        // TODO add your handling code here:
        logged_In = false;
        this.setVisible(false);
        gui.setVisible(true);
        gui.setLogged(false);
        gui.setLogged_In(null);
        gui.update("Success Logged out", "graphical_UI");
    }//GEN-LAST:event_log_outActionPerformed

    private void back_to_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_to_mainActionPerformed
        // TODO add your handling code here:
        gui.setVisible(true);
        logged_In = true;
        this.setVisible(false);
        gui.update("Success Still Logged In", "graphical_UI");
        gui.setLogged_In(this);
        gui.setLogged(true);
    }//GEN-LAST:event_back_to_mainActionPerformed

    private void confirm_payment_amount_paidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_payment_amount_paidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_payment_amount_paidActionPerformed

    private void confirm_payment_submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_payment_submit_btnActionPerformed
        // TODO add your handling code here:
        String person_paying = confirm_payment_person_paid.getText();
        String amount = confirm_payment_amount_paid.getText();
        String date = confirm_payment_date_paid.getText();
        
        cmd_handler.handlePaymentCommand(person_paying, amount, date, user);
    }//GEN-LAST:event_confirm_payment_submit_btnActionPerformed

    private void confirm_payment_reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_payment_reset_btnActionPerformed
        // TODO add your handling code here:
        confirm_payment_person_paid.setText("");
        confirm_payment_amount_paid.setText("");
        confirm_payment_date_paid.setText("");
    }//GEN-LAST:event_confirm_payment_reset_btnActionPerformed

    private void enter_bill_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_bill_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_bill_amountActionPerformed

    private void show_hide_enter_bill_tabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_hide_enter_bill_tabActionPerformed
        // TODO add your handling code here:
        if (show_hide_enter_bill_tab.getText().equals("Hide")) {
            panel_for_enter_bill.setVisible(false);
            show_hide_enter_bill_tab.setText("Show");
        } 
        else 
        {
            panel_for_enter_bill.setVisible(true);
            show_hide_enter_bill_tab.setText("Hide");
        }
    }//GEN-LAST:event_show_hide_enter_bill_tabActionPerformed

    private void enter_payment_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_payment_menu_itemActionPerformed
        // TODO add your handling code here:
        panel_for_enter_bill.setVisible(true);
        show_hide_enter_bill_tab.setText("Hide");
    }//GEN-LAST:event_enter_payment_menu_itemActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void enter_payment_billItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_enter_payment_billItemStateChanged
        // TODO add your handling code here:
        if(enter_payment_bill.getSelectedItem().toString().equals("Utility Bill"))
        {
            enter_payment_util_type.setVisible(true);
        }
        else
        {
            enter_payment_util_type.setVisible(false);
        }
    }//GEN-LAST:event_enter_payment_billItemStateChanged

    private void enter_payment_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_payment_billActionPerformed

    }//GEN-LAST:event_enter_payment_billActionPerformed

    private void enter_bill_submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_bill_submit_buttonActionPerformed

        String billtype = enter_payment_bill.getSelectedItem().toString();
        String amount = "";
        String date = "";
        
        boolean dat = false;
        boolean amt = false;
        boolean bill = false;
        
        if (!enter_bill_amount.getText().equals(""))//Checks if empty
        {
            amount = enter_bill_amount.getText(); 
            enter_bill_amount_label.setForeground(Color.black);
            amt = true;
        }
        else
        {
            enter_bill_amount_label.setForeground(Color.red);
        }

  
        if (!(enter_bill_date.getText()).equals(""))//Format date
        {
            if ((enter_bill_date.getText().charAt(2) == '/') && (enter_bill_date.getText().charAt(5) == '/'))
            {
                if(enter_bill_date.getText().length() == 10)
                {
                    date = enter_bill_date.getText(); 
                    enter_bill_date_label.setForeground(Color.black);
                    dat = true;
                }
                else
                {
                    enter_bill_date_label.setForeground(Color.red);
                }
            }
            else
            {
                enter_bill_date_label.setForeground(Color.red);
            }
        }
        else
        {
            enter_bill_date_label.setForeground(Color.red);
        }
        
        
        String item = "";
        if (!billtype.contains("Select"))
        {
            if(billtype.equals("Utility Bill"))
            {
                item = enter_payment_util_type.getSelectedItem().toString();
                enter_details_isSelected.setForeground(Color.black);
                bill = true;
            }
            else
            {
                if (!enter_bill_item.getText().equals(""))//check empty
                {
                    item =  enter_bill_item.getText();
                    bill = true;
                    enter_details_isSelected.setForeground(Color.black);
                }
                else
                {
                    enter_bill_date_label.setForeground(Color.red);
                }
            }
        }
        else
        {
            enter_details_isSelected.setForeground(Color.red);
        }        
       
        
        if (dat && amt && bill)
        {
            cmd_handler.handleEnterBillCommand(billtype, amount,date, item);
            enter_payment_isSubmitted.setText("Submitted!");
        }
        else
        {
            enter_payment_isSubmitted.setText("Incomplete");
        }
    }//GEN-LAST:event_enter_bill_submit_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_to_main;
    private javax.swing.JTabbedPane bills;
    private javax.swing.JTextField confirm_payment_amount_paid;
    private javax.swing.JTextField confirm_payment_date_paid;
    private javax.swing.JTextField confirm_payment_person_paid;
    private javax.swing.JButton confirm_payment_reset_btn;
    private javax.swing.JButton confirm_payment_submit_btn;
    private javax.swing.JTextField enter_bill_amount;
    private javax.swing.JLabel enter_bill_amount_label;
    private javax.swing.JTextField enter_bill_date;
    private javax.swing.JLabel enter_bill_date_label;
    private javax.swing.JTextField enter_bill_item;
    private javax.swing.JLabel enter_bill_item_label;
    private javax.swing.JButton enter_bill_reset_button;
    private javax.swing.JButton enter_bill_submit_button;
    private javax.swing.JLabel enter_details_isSelected;
    private javax.swing.JComboBox<String> enter_payment_bill;
    private javax.swing.JLabel enter_payment_isSubmitted;
    private javax.swing.JMenuItem enter_payment_menu_item;
    private javax.swing.JComboBox<String> enter_payment_util_type;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JButton log_out;
    private javax.swing.JPanel panel_for_enter_bill;
    private javax.swing.JTextArea personal_message_text_area;
    private javax.swing.JButton show_hide_enter_bill_tab;
    private javax.swing.JLabel welcome_user;
    // End of variables declaration//GEN-END:variables
}
